### ISSUE TITLE
All TR Walldecals Calculate Collision & Trishapes should be merged

### ISSUE THREAD

**Issue by MwGek** [TD-Addon/TamrielDataMain#1]
To improve FPS the wall decals in TR data should be optimized.

![image](https://user-images.githubusercontent.com/76392007/102712086-8b1bb380-42be-11eb-842b-ab3094ade237.png)
![image](https://user-images.githubusercontent.com/76392007/102712128-e0f05b80-42be-11eb-8e94-59ea3851bb3b.png)

**Comment by MwGek** [comment]
Merge this fix: https://www.tamriel-rebuilt.org/asset/optimized-wall-decals

**Comment by cheflul** [comment]
merged the fix
