### ISSUE TITLE
Caspering on T_Glb_Var_SkeletonTorso_01

### ISSUE THREAD

**Issue by Delemis** [TD-Addon/TamrielDataMain#10]
T_Glb_Var_SkeletonSpine_01 is caspering due to the asset missing the sacrum, which the spine of T_Glb_Var_SkeletonTorso_01 features.

![image](https://user-images.githubusercontent.com/59373809/213944883-f05ccbca-dc36-4d49-a247-174d56995e41.png)
![image](https://user-images.githubusercontent.com/59373809/213944891-29c44c43-309c-4681-b55f-6c3fdcf5d0ed.png)

**Comment by Delemis** [comment]
Submitted on behalf of int dev CherryGoats (Cherry on discord) so if you have questions you need to ask, you can direct them to her.

**Comment by antonisauren** [comment]
Rotation must be hand adjusted to touch the ground. There are 417 usages in TR itself. Changing mesh orientation is out of question.
