### ISSUE TITLE
PI meshes missing from Tamriel_Data v10.1

### ISSUE THREAD

**Issue by MasssiveJuice08** [TD-Addon/TamrielDataMain#13]
The following static objects are missing their meshes in the latest release:

File not found: [STAT] "T_Pi_FloraYN_TreeVine_03" -> "Data Files\\meshes\\pi\\x\\yn_treevine_03.nif"
File not found: [STAT] "T_Pi_FloraYN_TreeVine_04" -> "Data Files\\meshes\\pi\\x\\yn_treevine_04.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_07" -> "Data Files\\meshes\\pi\\x\\yn_tree_07.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_08" -> "Data Files\\meshes\\pi\\x\\yn_tree_08.nif"
File not found: [STAT] "T_Pi_FloraYN_TreeVine_01" -> "Data Files\\meshes\\pi\\x\\yn_treevine_01.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_05" -> "Data Files\\meshes\\pi\\x\\yn_tree_05.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_10" -> "Data Files\\meshes\\pi\\x\\yn_tree_10.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_09" -> "Data Files\\meshes\\pi\\x\\yn_tree_09.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_02" -> "Data Files\\meshes\\pi\\x\\yn_tree_02.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_03" -> "Data Files\\meshes\\pi\\x\\yn_tree_03.nif"
File not found: [STAT] "T_Pi_FloraYN_TreeVine_02" -> "Data Files\\meshes\\pi\\x\\yn_treevine_02.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_04" -> "Data Files\\meshes\\pi\\x\\yn_tree_04.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_06" -> "Data Files\\meshes\\pi\\x\\yn_tree_06.nif"
File not found: [STAT] "T_Pi_FloraYN_Tree_01" -> "Data Files\\meshes\\pi\\x\\yn_tree_01.nif"
File not found: [STAT] "T_Pi_FloraYN_TreeVine_05" -> "Data Files\\meshes\\pi\\x\\yn_treevine_05.nif"

**Comment by antonisauren** [comment]
They got moved to /f/ and mesh paths in game objects are adjusted.
