### ISSUE TITLE
Error in PT_Data check in MWSE Lua Code

### ISSUE THREAD

**Issue by Toriansel** [TD-Addon/TamrielDataMain#15]
https://github.com/TD-Addon/TamrielDataMain/blob/e9eec127f3f1bdcd2707d0456709bc37dad84b2c/00%20Data%20Files/MWSE/mods/TamrielData/main.lua#L53

I suspect the PT_Data at in this if loop should be a PC_Data.

**Comment by Kynesifnar** [comment]
That would be a problem, though this function is not present in the yet-to-be merged version of the MWSE addon (https://github.com/TD-Addon/TD_Lua_Addons) given that the BSAs are no longer being used by Tamriel_Data.
