### ISSUE TITLE
2 Books Issues

### ISSUE THREAD

**Issue by 1John418** [TD-Addon/TamrielDataMain#7]
- T_bk_GlassInMorrowind_TR mentions Bodr**e**m, which should be changed to Bodr**u**m.
- T_bk_HowtoterstHeretics_TR has a typo: reasonably have and **are** you are: https://media.discordapp.net/attachments/800812964658675783/996742986178240562/Morrowind_2022-07-12_16.55.35.640.jpg?width=1001&height=563

**Comment by Assumeru** [comment]
Fixed the latter, left the former as the description of the town is suspect anyway.
